[pytest]
DJANGO_SETTINGS_MODULE = mysite.settings
pythonpath = lightone_v2_django
testpaths =
    tests
    lightone_v2_django/dashboard
    lightone_v2_django/lightone/tests
python_files = tests.py test_*.py *_tests.py
addopts = -ra
