# Generated by Django 4.2.30 on 2026-07-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(blank=True, null=True, verbose_name='세션일')),
                ('exercise_name', models.CharField(blank=True, max_length=120, verbose_name='주요 운동')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='세트')),
                ('reps', models.PositiveIntegerField(default=10, verbose_name='회수')),
                ('weight_kg', models.FloatField(default=0, verbose_name='중량(kg)')),
                ('pain_response', models.FloatField(default=0, verbose_name='통증 반응 (0-10)')),
                ('rpe', models.FloatField(default=5, verbose_name='RPE 운동 자각도 (0-10)')),
                ('form_accuracy', models.FloatField(default=7, verbose_name='자세 정확도 (0-10)')),
                ('jatc_score', models.FloatField(default=70, verbose_name='JATC 점수 (0-100)')),
                ('qs_score', models.FloatField(default=0, verbose_name='QS 점수')),
                ('route', models.CharField(choices=[('AUTO', 'AUTO — 일반 진행 가능'), ('REVIEW', 'REVIEW — 트레이너 검토 필요'), ('BLOCK', 'BLOCK — 안전 신호 발생')], default='AUTO', max_length=10, verbose_name='위험 라우팅')),
                ('qc_status', models.CharField(choices=[('PASS', 'PASS — 정상'), ('CHECK', 'CHECK — 재확인 필요'), ('FAIL', 'FAIL — 분석 불가')], default='PASS', max_length=10, verbose_name='촬영 QC')),
                ('shoulder_tilt', models.FloatField(default=0, verbose_name='어깨 기울기(도)')),
                ('pelvis_tilt', models.FloatField(default=0, verbose_name='골반 기울기(도)')),
                ('spine_alignment', models.FloatField(default=7, verbose_name='첥추 정렬도(0-10)')),
                ('knee_alignment', models.FloatField(default=7, verbose_name='무릅 정렬도(0-10)')),
                ('ankle_alignment', models.FloatField(default=7, verbose_name='발목 정렬도(0-10)')),
                ('lr_deviation', models.FloatField(default=0, verbose_name='좌우 편차(도)')),
                ('memo', models.TextField(blank=True, verbose_name='트레이너 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_sessions', to='members.member')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to='accounts.trainerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
