# Generated by Codex on 2026-07-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightone', '0004_membersession_function_training_score_and_more'),
    ]

    # The parallel 0005_replace_indicator_with_membersession_indicator
    # migration recreates Indicator with the member_session relation. Keeping
    # this branch as a no-op preserves migration history without attempting to
    # alter the deleted legacy session field.
    operations = []
