# Generated by Django 6.0.6 on 2026-07-06 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lightone', '0004_membersession_function_training_score_and_more'),
    ]

    # This branch targeted the pre-replacement Indicator schema. The active
    # replacement branch creates the current Indicator model directly, while
    # later migrations supply the MemberSession field changes.
    operations = []
