# Generated by Django 5.2.15 on 2026-07-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0007_merge_20260710_0000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersession",
            name="trainer_name",
            field=models.CharField(default="LIGHTONE Trainer", max_length=80),
        ),
        migrations.AlterField(
            model_name="strategyitem",
            name="priority",
            field=models.CharField(default="high", max_length=30),
        ),
        migrations.AlterField(
            model_name="strategyitem",
            name="status",
            field=models.CharField(default="needs_action", max_length=40),
        ),
    ]
