# Generated by Django 4.2.30 on 2026-07-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='주차 시작일')),
                ('week_end', models.DateField(verbose_name='주차 종료일')),
                ('avg_qs', models.FloatField(default=0, verbose_name='평균 QS 점수')),
                ('avg_pain', models.FloatField(default=0, verbose_name='평균 통증 반응')),
                ('avg_rpe', models.FloatField(default=0, verbose_name='평균 RPE')),
                ('session_count', models.PositiveIntegerField(default=0, verbose_name='세션 횟수')),
                ('posture_score', models.FloatField(default=0, verbose_name='체형 종합 점수')),
                ('auto_count', models.PositiveIntegerField(default=0, verbose_name='AUTO 횟수')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='REVIEW 횟수')),
                ('block_count', models.PositiveIntegerField(default=0, verbose_name='BLOCK 횟수')),
                ('trainer_comment', models.TextField(blank=True, verbose_name='트레이너 콘멘트')),
                ('next_goal', models.TextField(blank=True, verbose_name='다음 주차 목표')),
                ('reregistration_signal', models.BooleanField(default=False, verbose_name='재등록 상담 신호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='members.member')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trainerprofile')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
