# Generated by Django 4.2.30 on 2026-07-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='나이')),
                ('sex', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('goal', models.CharField(choices=[('posture', '체형교정'), ('pain', '통증감소'), ('strength', '스트렉스 감소'), ('weight', '체중관리'), ('rehab', '기능회복'), ('performance', '운동능력 향상')], default='posture', max_length=20, verbose_name='운동 목표')),
                ('discomfort_area', models.CharField(blank=True, max_length=120, verbose_name='불편 부위')),
                ('memo', models.TextField(blank=True, verbose_name='특이사항')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 회원')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.trainerprofile')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
